# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-08 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appaxf', '0008_auto_20181102_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.CharField(max_length=256)),
                ('createtime', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appaxf.User')),
            ],
        ),
        migrations.CreateModel(
            name='Orderinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appaxf.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appaxf.Order')),
            ],
        ),
    ]
